Feat/ss add target model
twinkling-gecko/sparkling-gecko pull request #23
Opened 2021-01-25 15:39 UTC by tatikaze

モデル設計のレビュー
jamboardを元に作成

2021-01-25 15:42 UTC, tatikaze commented on src/shallow-snake/src/aodaishou/api/entity/ItemValue.ts
> +
dbのカラム名をキャメルケースになってしまう
'itemId'

2021-02-08 01:56 UTC, s10akir requested changes
![](https://user-images.githubusercontent.com/34061817/107167463-4c6fc300-69fc-11eb-9b37-deb0b2b554ac.png)

2021-02-08 01:56 UTC, s10akir commented on src/shallow-snake/src/aodaishou/api/entity/Item.ts
> +  imageUrl: string
非requiredにしてほしい（default valueをnullとかでいい）

2021-02-08 02:36 UTC, s10akir approved these changes
![](https://user-images.githubusercontent.com/34061817/107169716-eb4aee00-6a01-11eb-9c79-058b4f3dd5ca.png)

2021-02-08 02:52 UTC, merged